
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tester.flagger.app
  resources:
  - testers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tester.flagger.app
  resources:
  - testers/finalizers
  verbs:
  - update
- apiGroups:
  - tester.flagger.app
  resources:
  - testers/status
  verbs:
  - get
  - patch
  - update
