# permissions for end users to view testers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tester-viewer-role
rules:
- apiGroups:
  - tester.flagger.app
  resources:
  - testers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tester.flagger.app
  resources:
  - testers/status
  verbs:
  - get
